### PR TITLE
feat:run apple_vision_recognition_text in other thread to make ui smooth

### PR DESCRIPTION
**Pull request by alihassan143**
#3 closes

### CODE REVIEW

**Comment by alihassan143** [comment]
@Knightro63 kindly take a look

**Review by Knightro63 — CHANGES_REQUESTED** [review]
This change is overriding AppleVisionScannerPlugin not AppleVisionRecognizeTextPlugin. Please make changes before this is abled to be merged.

**Comment by alihassan143** [comment]
@Knightro63  oh i did'nt see i will revert changes and implement in correct plugin

**Comment by alihassan143** [comment]
@Knightro63  changes applied to correct file

**Comment by alihassan143** [comment]
@Knightro63 can you look into changes

**Review by Knightro63 — APPROVED** [review]

**Comment by Knightro63** [comment]
This has a serious memory leak issue. This would need to be resolved before another pull request.

**Pull request merged**
